version: 2

sources:
  - name: sap
    description: This is the ERP sources from adventure works. With data from sales, products, HR, and others.
    database: adventure-works-432501 
    schema: sap_adw
    tables:
      - name: product
        description: Table with product data. Products sold or used in the manfacturing of sold products.
        columns:
          - name: PRODUCTID
            description: Primary key for product records.
            tests:
              - unique
              - not_null
          - name: NAME
            description: Name of the product
          - name: PRODUCTNUMBER
            description: Unique product identification number.
            tests:
              - unique 
              - not_null
          - name: MAKEFLAG
            description: >
              Flag that identifies if the product is manufactured by Adventure Work or purchased.
              0 = Product is purchased, 1 = Product is manufactured in-house.
            tests:
              - accepted_values:
                  values:
                    - 'true'
                    - 'false'
                  quote: false

          - name: FINISHEDGOODSFLAG
            description: >
              Flag that identifies if the product will be sold by Adventure Work 
              or will be used in production of other products.
              0 = Product is not a salable item. 1 = Product is salable.
            tests:
              - accepted_values:
                  values:
                    - 'true'
                    - 'false'
                  quote: false
                  
          - name: COLOR
            description: Color of the product
          - name: SAFETYSTOCKLEVEL
            description: Minimum inventory quantity.
          - name: REORDERPOINT
            description: Inventory level that triggers a purchase order or work order.
          - name: STANDARDCOST
            description: Standard cost of the product.
          - name: LISTPRICE
            description: Selling price.
          - name: SIZE
            description: Product size.
          - name: SIZEUNITMEASURECODE
            description: Unit of measure for Size column.
          - name: WEIGHTUNITMEASURECODE
            description: Unit of measure for Weight column
          - name: WEIGHT
            description: Product weight.
          - name: DAYSTOMANUFACTURE
            description: Number of days required to manufacture the product.
          - name: PRODUCTLINE
            description: >
              Product line.
              R = Road, M = Mountain, T = Touring, S = Standard.
          - name: CLASS
            description: >
                Class of the product
                H = High, M = Medium, L = Low
          - name: STYLE
            description: >
              Style of the product.
              W = Womens, M = Mens, U = Universal
          - name: PRODUCTSUBCATEGORYID
            description: Product is a member of this product subcategory. Foreign key to productsubcategory table.
          - name: PRODUCTMODELID
            description: Product is a member of this product model. Foreign key to productmodel table
          - name: SELLSTARTDATE
            description: Date the product was available for sale.
          - name: SELLENDDATE
            description: Date the product was no longer available for sale.
          - name: DISCONTINUEDDATE
            description: Date the product was discontinued.
          - name: ROWGUID
          - name: MODIFIEDDATE
            description: Date and time the record was last updated.
      - name: productsubcategory
        description:  Products subcategories.
        columns:
          - name: PRODUCTSUBCATEGORYID
            description: Primary key for Product Subcategory records.
            tests:
              - unique
              - not_null
          - name: PRODUCTCATEGORYID
            description: Product category identification number. Foreign key to productcategory table.
            tests:
              - not_null
          - name: NAME
            description: Subcategory description.
          - name: ROWGUID
          - name: MODIFIEDDATE
            description: Date and time the record was last updated.

      - name: productcategory
        description: High-level product categorization.
        columns:
          - name: productcategoryid
            description: Primary key for Product Category records
            tests:
              - unique 
              - not_null
          - name: NAME
            description: Category description.
          - name: ROWGUID
          - name: MODIFIEDDATE
            description: Date and time the record was last updated.
      - name: address
        description: Street address information for customers, employees, and vendors.
        columns:
          - name: ADDRESSID
            description: Primary key for Address records.
            tests:
              - unique
              - not_null
          - name: ADDRESSLINE1
            description: First street address line.
          - name: ADDRESSLINE2
            description: Second street address line.
          - name: CITY
            description: Name of the city.
          - name: STATEPROVINCEID
            description: Unique identification number for the state or province. Foreign key to stateprovince table.
            tests:
              - not_null
          - name: POSTALCODE
            description: Postal code for the street address.
          - name: SPATIALLOCATION
            description: Latitude and longitude of this address, saved in geographical type.
          - name: ROWGUID
          - name: MODIFIEDDATE
            description: Date and time the record was last updated

      - name: stateprovince
        description: State and province lookup table
        columns:
          - name: STATEPROVINCEID
            description: Primary key for StateProvince records
            tests:
              - unique 
              - not_null
          - name: STATEPROVINCECODE
            description: ISO standard state or province code.
            tests:
              - unique 
              - not_null
          - name: COUNTRYREGIONCODE
            description: ISO standard country or region code. Foreign key to countryregion table.
            tests:
              - not_null
          - name: ISONLYSTATEPROVINCEFLAG
            description: >
              Flag that indicated if the state code exists.
              0 = StateProvinceCode exists. 1 = StateProvinceCode unavailable, using CountryRegionCode.
            tests:
              - accepted_values:
                  values:
                    - 'true'
                    - 'false'
                  quote: false
          - name: NAME
            description: State or province description.
          - name: TERRITORYID
            description: ID of the territory in which the state or province is located.
            tests:
              - not_null
          - name: ROWGUID
          - name: MODIFIEDDATE
            description: Date and time the record was last updated.

      - name: countryregion
        description: Lookup table containing the ISO standard codes for countries and regions.
        columns:
          - name: COUNTRYREGIONCODE
            description: ISO standard code for countries and regions. And primary key of the table.
            tests:
              - unique 
              - not_null
          - name: NAME
            description: Country or region name.
          - name: MODIFIEDDATE
            description: Date and time the record was last updated.

      - name: customer
        description: >
          Customer information. Can be both individuals and stores that resells Adventure Works products.
          That is why personid and storeid columns will have nulls.
        columns:
          - name: CUSTOMERID
            description: Primary key for the Customers records.
            tests:
              - unique
              - not_null
          - name: PERSONID
            description: Foreign key to person table.
          - name: STOREID
            description: Foreign key to store table.
          - name: TERRITORYID
            description: ID of the territory in which the customer is located.
          - name: ROWGUID
          - name: MODIFIEDDATE
            description: Date and time the record was last updated.
            
      - name: person
        description: 'Human beings involved with AdventureWorks: employees, customer contacts, and vendor contacts.'
        columns:
          - name: BUSINESSENTITYID
            description: Primary key for Person records.
            tests:
              - unique
              - not_null
          - name: PERSONTYPE
            description: >
              Primary type of person: SC = Store Contact, IN = Individual (retail) customer, 
              SP = Sales person, EM = Employee (non-sales), VC = Vendor contact, GC = General contact.
            tests:
              - accepted_values:
                  values:
                    - "SC"
                    - "IN"
                    - "SP"
                    - "EM"
                    - "VC"
                    - "GC"
          - name: NAMESTYLE
            description: >
              0 = The data in FirstName and LastName are stored in western style (firs name, last name) order. 
              1 = Eastern style (last name, first name) order.
            tests:
              - accepted_values:
                  values:
                    - "TRUE"
                    - "FALSE"
                  quote: false
          - name: TITLE
            description: A courtesy title. For example, Mr. or Ms.
          - name: FIRSTNAME
            description: First name of the person.
          - name: MIDDLENAME
            description: Middle name or middle initial of the person.
          - name: LASTNAME
            description: Last name of the person.
          - name: SUFFIX
            description: Surname suffix. For example, Sr. or Jr.
          - name: EMAILPROMOTION
            description: >
              Categorizing people by their wish to receive promotion by email.
              0 = Contact does not wish to receive e-mail promotions, 
              1 = Contact does wish to receive e-mail promotions from AdventureWorks, 
              2 = Contact does wish to receive e-mail promotions from AdventureWorks and selected partners.
            tests:
              - accepted_values:
                  values:
                    - "0"
                    - "1"
                    - "2"
                  quote: false
          - name: ADDITIONALCONTACTINFO
            description: Additional contact information about the person stored in xml format.
          - name: DEMOGRAPHICS
            description: >
              Personal information such as hobbies, and income collected from online shoppers. 
              Used for sales analysis.
          - name: ROWGUID
          - name: MODIFIEDDATE
            description: Date and time the record was last updated.

      - name: store
        description: Customers (resellers) of Adventure Works products.
        columns:
          - name: BUSINESSENTITYID
            description: Primary key for the store customers records
            tests:
              - unique 
              - not_null
          - name: NAME
            description: Name of the store.
          - name: SALESPERSONID
            description: ID of the sales person assigned to the customer. Foreign key to salesperson table.
            tests:
              - not_null
          - name: DEMOGRAPHICS
            description: >
              Demographic informationg about the store such as the number of employees, 
              annual sales and store type.
          - name: ROWGUID
          - name: MODIFIEDDATE
            description: Date and time the record was last updated.
            
      - name: salesperson
        description: Sales representative current information.
        columns:
          - name: BUSINESSENTITYID
            description: Primary key for SalesPerson records.
            tests:
              - unique
              - not_null
          - name: TERRITORYID
            description: Territory currently assigned to.
          - name: SALESQUOTA
            description: Projected yearly sales.
          - name: BONUS
            description: >
              Bonus due if quota is met.
              Default: 0.00
          - name: COMMISSIONPCT
            description: >
              Commision percent received per sale.
              Default: 0.00 
          - name: SALESYTD
            description: >
              Sales total year to date.
              Default: 0.00
          - name: SALESLASTYEAR
            description: >
              Sales total of previous year.
              Default: 0.00
          - name: ROWGUID
          - name: MODIFIEDDATE
            description: Date and time the record was last updated.